<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:task="http://www.springframework.org/schema/task"
       xsi:schemaLocation="
       http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.0.xsd
       http://www.springframework.org/schema/task
       http://www.springframework.org/schema/task/spring-task-4.0.xsd">

    <task:annotation-driven executor="asyncExecutor" proxy-target-class="true"/>

    <task:executor id="asyncExecutor" pool-size="30-300" queue-capacity="10" rejection-policy="CALLER_RUNS"/>

    <!--<bean id="myAsyncUncaughtExceptionHandler"
          class="com.valueplus.business.app.common.asyncException.MyAsyncUncaughtExceptionHandler"/>-->
</beans>